name: "k8s-sync"
description: "Syncs the latest docker image to the k8s repo"
author: "Zak Shearman"

inputs:
  manifest-path:
    description: "The path to the manifest file to sync (e.g. fleet.yaml)"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Checkout"
      uses: "actions/checkout@v3"
      with:
        ref: "deployment"

    - name: "Lowercase Repo"
      shell: "bash"
      run: |
        echo "REPOSITORY=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    - name: "Update deployment file"
      shell: "bash"
      # git commit -a automatically adds files that have been modified
      run: |
        sed -i 's|image: .*|image: ghcr.io/${{ env.REPOSITORY }}:${{ github.sha }}|g' ${{ inputs.manifest-path }}

        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git commit -am "Update deployment to ${{ github.sha }}"
        git push
