name: "go-single-publish"
description: "Publishes a single go binary to the container registry built from a dockerfile"
author: "Zak Shearman"

inputs:
  registry-password:
    description: "The password used to login to the container registry"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Checkout"
      uses: "actions/checkout@v3"

    # Identifies if the branch is main or not and therefore whether we should tag the image as latest
    # Creates the tags for use later (either hash or latest and hash)
    - name: "Identify Environment"
      shell: bash
      run: |
        tag_prefix="ghcr.io/${{ github.repository }}"
        tags=""
        
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          tags="$tag_prefix:${{ github.sha }},$tag_prefix:latest"
        elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
          tags="$tag_prefix:${{github.event.pull_request.head.sha}},$tag_prefix:${{ github.event.number }}"
        fi
        
        echo "TAGS=$tags" >> "$GITHUB_ENV"

    - name: "Login to container registry"
      uses: "docker/login-action@v2"
      with:
        registry: "ghcr.io"
        username: "${{ github.actor }}"
        password: "${{ inputs.registry-password }}"

    - name: "Set up Docker Buildx"
      uses: "docker/setup-buildx-action@v2"

    - name: "Build and push"
      uses: "docker/build-push-action@v4"
      with:
        context: "."
        file: "./Dockerfile"
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ env.TAGS }}
