name: "maven-publish-release"
description: "Builds and publishes a Java project to the releases repository"
author: "BomBardyGamer"

inputs:
  publish-task:
    description: "The Gradle task to publish the package"
    default: "publishMavenPublicationToReleaseRepository"
  root-directory:
    description: "The relative path to the root directory of the project, if the Java project is not in the root"
    default: "."
  maven-username:
    description: "The username to use when authenticating with the Maven repository"
  maven-password:
    description: "The password to use when authenticating with the Maven repository"

runs:
  using: "composite"
  steps:
    - name: "Checkout repository"
      uses: "actions/checkout@v3"

    - name: "Get Commit Hash"
      id: "commit"
      uses: "pr-mpt/actions-commit-hash@v3"

    - name: "Set up Java"
      uses: "actions/setup-java@v3"
      with:
        java-version: "21"
        distribution: "zulu"

    - name: "Validate Gradle wrapper"
      uses: "gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b"
      with:
        wrapper-directory: "${{ inputs.root-directory }}/gradle/wrapper"
        gradle-executable: "${{ inputs.root-directory }}/gradlew"

    - name: "Publish package"
      uses: "gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1"
      with:
        arguments: "${{ inputs.publish-task }}"
        build-root-directory: "${{ inputs.root-directory }}"
      env:
        MAVEN_USERNAME: "${{ inputs.maven-username }}"
        MAVEN_SECRET: "${{ inputs.maven-password }}"
        RELEASE_VERSION: "${{ github.ref_name }}"
