name: "maven-publish-development"
description: "Builds and publishes a Java project to the development repository"
author: "BomBardyGamer"

inputs:
  publish-task:
    description: "The Gradle task to publish the package"
    default: "publishMavenPublicationToDevelopmentRepository"
  root-directory:
    description: "The relative path to the root directory of the project, if the Java project is not in the root"
    default: "."
  maven-username:
    description: "The username to use when authenticating with the Maven repository"
  maven-password:
    description: "The password to use when authenticating with the Maven repository"

runs:
  using: "composite"
  steps:
    - name: "Checkout repository"
      uses: "actions/checkout@v4"

    - name: "Get Commit Hash"
      id: "commit"
      uses: "prompt/actions-commit-hash@v3"

#    - name: "Set up Java"
#      uses: "actions/setup-java@v3"
#      with:
#        java-version: "21"
#        distribution: "zulu"
#
#    - name: "Setup Gradle"
#      uses: "gradle/actions/setup-gradle@v4"

    - name: "Publish package"
      shell: bash
      run: "gradle ${{ inputs.publish-task }}"
      env:
        MAVEN_USERNAME: "${{ inputs.maven-username }}"
        MAVEN_SECRET: "${{ inputs.maven-password }}"
        COMMIT_HASH: "${{ steps.commit.outputs.hash }}"
        COMMIT_HASH_SHORT: "${{ steps.commit.outputs.short }}"
