# Left over from testing building separately from publishing - royal PITA.
# Probably continue at some point but not now

#name: "go-publish-only-single"
#description: "Pulls an artifact from the build-single job and publishes it to the container registry"
#author: "Zak Shearman"
#
#inputs:
#  registry-password:
#    description: "The password used to login to the container registry"
#    required: true
#
#runs:
#  using: "composite"
#  steps:
#    - name: "Checkout"
#      uses: "actions/checkout@v4"
#
#    - name: "Add env vars"
#      shell: bash
#      run: |
#        echo "LOCAL_REGISTRY_PATH=${{ github.workspace }}/registry" >> "$GITHUB_ENV"
#        echo "LOCAL_REGISTRY_ADDRESS=localhost:5000" >> "$GITHUB_ENV"
#
#    - name: Download Docker registry data from build job
#      uses: actions/download-artifact@v3
#      with:
#        name: docker-registry-data
#        path: ${{ env.LOCAL_REGISTRY_PATH }}
#
#    - name: Start Docker registry
#      shell: bash
#      run: |
#        docker run --rm --detach --publish 5000:5000 \
#          --volume LOCAL_REGISTRY_PATH:/var/lib/registry \
#          --name registry registry:2
#        sleep 2
#
#    - name: "Import images"
#      shell: bash
#      run: |
#        for image in ${LOCAL_DOCKER_TAGS//,/$'\n'}
#        do
#          docker pull $image
#        done
#
#    # Identifies if the branch is main or not and therefore whether we should tag the image as latest
#    # Creates the tags for use later (either hash or latest and hash)
#    - name: "Identify Environment"
#      uses: "emortalmc/actions/identify-environment-v1@main"
#      with:
#        registry-address: "ghcr.io"
#        env-output: "GHCR_DOCKER_TAGS"
#
#    - name: "Login to GitHub Container Registry"
#      uses: "docker/login-action@v2"
#      with:
#        registry: "ghcr.io"
#        username: "${{ github.actor }}"
#        password: "${{ inputs.registry-password }}"
#
#    - name: "Retag and push images"
#      shell: bash
#      run: |
#        for tag in $(echo $GHCR_DOCKER_TAGS | sed "s/,/ /g"); do
#          docker tag $LOCAL_REGISTRY_ADDRESS/${{ github.repository }}:$tag ghcr.io/${{ github.repository }}:$tag
#          docker push ghcr.io/${{ github.repository }}:$tag
#        done